server:
  port: ${PORT:0}
spring:
  application:
    name: users-ws
  devtools:
    restart:
      enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: Alpha2020
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka
  instance:
    instance-id: ${spring.application.name}${spring.application.instance_id:${random.value}}
#management:
#  endpoints:
#    web:
#      exposure:
#        include: mappings
#feign:
#  hystrix:
#    enabled: true
#logging:
#  level:
#    com:
#      app:
#        users:
#          data:
#            AlbumsServiceClient: debug
