server:
  port: ${PORT:0}
spring:
  application:
    name: departments-ws
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: Alpha2020
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka
  instance:
    instance-id: ${spring.application.name}${spring.application.instance_id:${random.value}}
management:
  endpoints:
    web:
      exposure:
        include: mappings
feign:
  hystrix:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types: application/json
    response:
      enabled: true
logging:
  file:
    name: /home/mohammedamine/Documents/workspace/master-microservices/logs/departments-ws.log
  level:
    com:
      quickapp:
        data:
          clients:
            UserServiceClient: debug
#  hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds=4000
#  hystrix.command.default.circuitBreaker.enabled=true<br>
#  hystrix.command.default.circuitBreaker.requestVolumeThreshold=2