server:
  port: 8010
spring:
  application:
    name: discovery-service
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defualtZone: http://localhost:8010/eureka