server:
  port: 8012
spring:
  application:
    name: cloud-config
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///home/USER/master-microservices/git-localconfig-repo
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
